# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Igor Queiroz
author-title: System Analyst and Full Stack Developer
gravatar: 36a4116f812ac8eb2d5c417636c8512d
email: igor.queiroz@whosnerd.com
twitter: eaglequeiroz
github: eaglequeiroz
googleplus: 
facebook: eaglequeiroz
linkedin: eaglequeiroz
bio: "Ambitious, tenacious, and well-accomplished Software Developer with 7+ years of experience. 
      Expert in working with Java EE, have a vast knowledge in various technologies that are part of the variety of systems 
      in Java for web. Armed with broad-based background and skills in the areas of providing appropriate solution to every 
      task needed. Training and display outstanding ability to manage, plan, coordinate, implement design practices 
      to bring significant improvements in efficiency, productivity and technical processes. Determined to implement earned 
      skills and knowledge for the rapid growth of the prospective organization by working effectively and consistently. 
      Motivated, alert to detail, communication with technical and business professionals, self-taught, share ideas, and 
      opened-mind to new ways of working."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 5
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 5
  - name: jQuery
    level: 4
  - name: Angular
    level: 4
  - name: Bootstrap
    level: 4  

back-end:
  - name: PHP
    level: 3
  - name: Ruby
    level: 2
  - name: Python
    level: 3
  - name: Java
    level: 5
  - name: SQL
    level: 5
  - name: C#
    level: 3

mobile:
  - name: Android
    level: 2

db:
  - name: MySQL
    level: 4
  - name: PostgreSQL
    level: 5
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 4
  - name: HQL
    level: 5

devops:
  - name: Jenkins
    level: 1
  - name: Git
    level: 5
  - name: Apache Maven
    level: 4
  - name: Continuous Integration
    level: 3
  - name: Continuous Delivery
    level: 2

methodologies:
  - name: Agile Methodologies
    level: 5
  - name: Scrum
    level: 5
  - name: RUP
    level: 3

others:
  - name: Web Services
    level: 5
  - name: REST
    level: 4
  - name: JEE, JSF, JPA, EJB, CDI
    level: 5
  - name: iReport, Jasper Reports
    level: 2
  - name: Hibernate
    level: 3
  - name: Ruby on Rails
    level: 3
  - name: Spring
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
