# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Igor Queiroz
author-title: Senior Java Web Developer
gravatar: 5e055e4d1deb8609fe31606f57f7292e
email: igorfqueirozz@gmail.com
twitter: eaglequeiroz
github: eaglequeiroz
googleplus: 
facebook: eaglequeiroz
linkedin: eaglequeiroz
bio: "I'm passionate about building intelligent solutions and to solve problems. Since 2008 I work with IT, acting a good part of my work experience as a Full-Stack Developer. I also had the opportunity to expand my IT knowledge by working for a full year as a Business Analyst, where I could live the whole building intelligent software process in a more strategic way and to implement the Scrum framework on a 10 Developers Team from the scratch."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 5
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 5
  - name: jQuery
    level: 4
  - name: Angular
    level: 4
  - name: React
    level: 4
  - name: Bootstrap
    level: 5  
  - name: Semantic UI
    level: 5  

back-end:
  - name: Java
    level: 5
  - name: Java EE
    level: 5
  - name: Spring
    level: 5
  - name: JSF
    level: 5  
  - name: JPA
    level: 5
  - name: EJB 3
    level: 5
  - name: CDI
    level: 5
  - name: Hibernate
    level: 5
  - name: Ruby
    level: 4
  - name: Ruby on Rails
    level: 4
  - name: SQL
    level: 5
  - name: NoSQL
    level: 3

mobile:
  - name: Android
    level: 2

db:
  - name: MySQL
    level: 4
  - name: PostgreSQL
    level: 5
  - name: SQL Server
    level: 4
  - name: Oracle
    level: 4
  - name: HQL
    level: 5

devops:
  - name: Jenkins
    level: 3
  - name: Git
    level: 5
  - name: Maven
    level: 5
  - name: Gradle
    level: 5
  - name: Continuous Integration
    level: 3
  - name: Continuous Delivery
    level: 3

methodologies:
  - name: Agile Methodologies
    level: 5
  - name: Scrum
    level: 5
  - name: RUP
    level: 4

others:
  - name: Web Services
    level: 5
  - name: REST
    level: 5
  - name: iReport
    level: 5 
  - name: Jasper Reports
    level: 5 

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
